#' Verify All Event Calculations
#'
#' Runs all event verification functions and combines results into a single Excel workbook
#' with multiple sheets. Provides a comprehensive validation of disease events, survival
#' outcomes, and failure patterns for EMBRACE-II data.
#'
#' @param save_excel Logical; whether to save results to Excel file (default: TRUE)
#'
#' @return A list containing all verification results with each element representing
#'   a different event verification dataset
#'
#' @keywords internal
#'
#' @import dplyr
#' @importFrom openxlsx createWorkbook addWorksheet writeData saveWorkbook
#'
#' @examples
#' \dontrun{
#' results <- emii_verify_all_events()
#' results <- emii_verify_all_events(save_excel = FALSE)
#' }
emii_verify_all_events <- function(save_excel = TRUE) {
  # Create list to store all verification results
  verification_results <- list()

  .data <- embraceR::load_embrace_ii()

    .data <- .data %>%
      embraceR::add_disease_events()

  # Run all verification functions
  verification_results$pelvic_event <- emii_add_pelvic_event_with_verification(.data)
  verification_results$pelvic_nodal <- emii_add_pelvic_nodal_event_with_verification(.data)
  verification_results$systemic_excl_pao <- emii_add_systemic_excl_pao_with_verification(.data)
  verification_results$paraaortic_nodal <- emii_add_paraaortic_nodal_with_verification(.data)
  verification_results$cancer_specific <- emii_add_cancer_specific_with_verification(.data)
  verification_results$nodal_control_incl_pao <- emii_add_nodalcontrol_incl_pao_with_verification(.data)
  verification_results$metastases <- add_metastases_with_verification(.data)
  verification_results$disease_control <- emii_add_disease_control_with_verification(.data)
  verification_results$progression_free <- emii_add_progression_free_survival_with_verification(.data)
  verification_results$locoregional <- add_locoregional_event_with_verification(.data)
  verification_results$distant_alone <- emii_add_distant_alone_with_verification(.data)
  if (save_excel) {
    # Create workbook
    wb <- createWorkbook()

    # Add each verification result as a separate worksheet
    for (name in names(verification_results)) {
      addWorksheet(wb, name)
      writeData(wb, name, verification_results[[name]])
    }

    # Add documentation sheet
    addWorksheet(wb, "Documentation")
    doc_text <- data.frame(
      Description = c(
        "Event Verification Results",
        "",
        "This workbook contains verification data for the following events:",
        "1. Pelvic Event - Combined local failure and pelvic nodal events",
        "2. Pelvic Nodal - Nodal events excluding para-aortic, other, and groin locations",
        "3. Systemic (excl. PAO) - Systemic failure excluding para-aortic metastases",
        "4. Para-aortic Nodal - Para-aortic nodal involvement",
        "5. Cancer-specific - Cancer-specific death events",
        "6. Nodal Control (incl. PAO) - Nodal control including para-aortic events",
        "7. Para-aortic Metastases - Presence of para-aortic metastases",
        "8. Metastases - Presence of metastases at various locations",
        "9. Disease Control - Combined local failure, nodal control (incl. PAO), or systemic (excl. PAO) events",
        "10. Progression-free Survival - Any disease event OR death",
        "11. Locoregional - Combined pelvic and para-aortic nodal events",
        "12. Distant alone - Systemic failure without para-aortic nodes and no local or nodal failures",
        "",
        "Each sheet contains:",
        "- Input columns used in the calculation",
        "- Output column(s) generated by the function",
        "- Patient IDs for traceability"
      )
    )
    writeData(wb, "Documentation", doc_text)

    # Save workbook
    saveWorkbook(wb, "event_verification_results.xlsx", overwrite = TRUE)
  }

  return(verification_results)
}
